---
# Tasks to create a new account on the ACME server
#
- name: Generating new EC SSL key - ACME account
  command: "openssl ecparam -genkey -name {{ acme_ssl_ecparam_curve }} -out {{ acme_ssl_account_key }}"

- name: Create ACME account
  acme_account:
    account_key_src: "{{ acme_ssl_account_key }}"
    state: present
    acme_directory: "{{ acme_ssl_directory }}"
    acme_version: "{{ acme_ssl_directory_version }}"
    terms_agreed: "{{ acme_ssl_terms_agreed }}"
    contact:
      - "mailto:{{ acme_ssl_admin_email }}"
