---
# What: Generate and request certificates via ACME
#
- name: 'Check certificate directory'
  file:
    path: "{{ acme_ssl_basedir }}/{{ certificate.domain }}"
    state: 'directory'
    mode: 0770
    owner: "{{ acme_ssl_owner }}"
    group: "{{ acme_ssl_owner }}"

- block:
    - name: "Check certificate validity - {{ certificate.domain }}"
      community.crypto.x509_certificate_info:
        path: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}.cer"
        valid_at:
          min_validity: "+{{ acme_ssl_validity_min }}d"
      register: 'ssl_cert_info'
    - name: "Check certificate validity - {{ certificate.domain }}"
      set_fact:
        acme_cert_valid: "{{ ssl_cert_info.valid_at.min_validity }}"
  rescue:
    - name: "Check certificate validity - {{ certificate.domain }}"
      set_fact:
        acme_cert_valid: false

- block:
  - name: "Clear old files - {{ certificate.domain }}"
    file:
      state: 'absent'
      path: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ item }}"
    loop:
      - "{{ certificate.domain }}.key"
      - "{{ certificate.domain }}.csr"
      - "{{ certificate.domain }}.cer"
      - "{{ certificate.domain }}_chain.cer"
      - "{{ certificate.domain }}_fullchain.cer"
      - 'ca.cer'

  - name: "Generating new EC SSL key - {{ certificate.domain }}"
    community.crypto.openssl_privatekey:
      path: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}.key"
      curve: "{{ acme_ssl_ecparam_curve }}"
      type: "{{ acme_ssl_type }}"
      mode: 0660
      owner: "{{ acme_ssl_owner }}"
      group: "{{ acme_ssl_owner }}"
    when: acme_ssl_type == 'ECC'

  - name: "Generating new SSL key - {{ certificate.domain }}"
    community.crypto.openssl_privatekey:
      path: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}.key"
      size: "{{ acme_ssl_rsa_bits }}"
      type: "{{ acme_ssl_type }}"
      mode: 0660
      owner: "{{ acme_ssl_owner }}"
      group: "{{ acme_ssl_owner }}"
    when: acme_ssl_type == 'RSA'

  - block:
    - name: "Generating SAN list - {{ certificate.domain }}"
      set_fact:
        san_list: "[ '{{ certificate.domain }}' ] + {{ certificate.altname }}"
    - name: "Adding SAN prefixes - {{ certificate.domain }}"
      set_fact:
        san_list: "{{ san_list | map('regex_replace', '^', 'DNS:') | list }}"
    - name: "Generating new CSR file with SAN - {{ certificate.domain }}"
      community.crypto.openssl_csr:
        path: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}.csr"
        privatekey_path: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}.key"
        common_name: "{{ certificate.domain }}"
        subject_alt_name: "{{ san_list }}"
        mode: 0660
        owner: "{{ acme_ssl_owner }}"
        group: "{{ acme_ssl_owner }}"
    when: certificate.altname is defined

  - name: "Generating new CSR file - {{ certificate.domain }}"
    community.crypto.openssl_csr:
      path: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}.csr"
      privatekey_path: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}.key"
      common_name: "{{ certificate.domain }}"
      subject_alt_name: "DNS:{{ certificate.domain }}"
      mode: 0660
      owner: "{{ acme_ssl_owner }}"
      group: "{{ acme_ssl_owner }}"
    when: certificate.altname is not defined

  - name: "Registering new ACME challenge - {{ certificate.domain }}"
    community.crypto.acme_certificate:
      account_key_src: "{{ acme_ssl_account_key }}"
      challenge: "{{ certificate.challenge | default(acme_ssl_default_challenge) }}"
      acme_directory: "{{ acme_ssl_directory }}"
      validate_certs: "{{ acme_ssl_directory_validate }}"
      acme_version: "{{ acme_ssl_directory_version }}"
      remaining_days: "{{ acme_ssl_validity_min }}"
      terms_agreed: "{{ acme_ssl_terms_agreed }}"
      csr: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}.csr"
      cert: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}.cer"
    register: 'acme_ssl_challenge_data'

  - block:
    - name: "Processing challenge - {{ certificate.domain }}"
      include_tasks:
        file: 'acme_{{ certificate.challenge | default(acme_ssl_default_challenge) }}_create.yml'

    - name: "Validating and finishing request - {{ certificate.domain }}"
      community.crypto.acme_certificate:
        account_key_src: "{{ acme_ssl_account_key }}"
        challenge: "{{ certificate.challenge | default(acme_ssl_default_challenge) }}"
        acme_directory: "{{ acme_ssl_directory }}"
        validate_certs: "{{ acme_ssl_directory_validate }}"
        acme_version: "{{ acme_ssl_directory_version }}"
        remaining_days: "{{ acme_ssl_validity_min }}"
        terms_agreed: "{{ acme_ssl_terms_agreed }}"
        csr: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}.csr"
        cert: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}.cer"
        chain: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}_chain.cer"
        fullchain: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ certificate.domain }}_fullchain.cer"
        data: "{{ acme_ssl_challenge_data }}"
      register: 'cert_validated'
      retries: 6
      delay: 60
      until: not cert_validated.failed

    - name: "Downloading Issuing CA certificate - {{ certificate.domain }}"
      uri:
        url: "{{ acme_ssl_ca_url }}"
        force: true
        status_code:
          - 200
          - 304
        validate_certs: "{{ acme_ssl_directory_validate }}"
        dest: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/ca.cer"
        mode: 0660
        owner: "{{ acme_ssl_owner }}"
        group: "{{ acme_ssl_owner }}"

    - name: "Downloading Issuing CA OCSP certificate - {{ certificate.domain }}"
      uri:
        url: "{{ acme_ssl_ocsp_url }}"
        force: true
        status_code:
          - 200
          - 304
        validate_certs: "{{ acme_ssl_directory_validate }}"
        dest: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/ocsp.cer"
        mode: 0660
        owner: "{{ acme_ssl_owner }}"
        group: "{{ acme_ssl_owner }}"

    always:
    - name: "Cleaning up challenge - {{ certificate.domain }}"
      include_tasks:
        file: 'acme_{{ certificate.challenge | default(acme_ssl_default_challenge) }}_cleanup.yml'
    when: acme_ssl_challenge_data is changed
  when: not acme_cert_valid

- name: "Sync certificates to Ansible Master - {{ certificate.domain }}"
  fetch:
    src: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ item }}"
    dest: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ item }}"
    fail_on_missing: false
    flat: true
  loop:
    - "{{ certificate.domain }}.key"
    - "{{ certificate.domain }}.csr"
    - "{{ certificate.domain }}.cer"
    - "{{ certificate.domain }}_chain.cer"
    - "{{ certificate.domain }}_fullchain.cer"
    - 'ca.cer'
    - 'ocsp.cer'
  when: not acme_ssl_local_ansible

- name: "Create destdir on target - {{ certificate.domain }}"
  file:
    path: "{{ acme_ssl_destdir }}/{{ certificate.domain }}"
    state: 'directory'
    mode: 0750
  delegate_to: "{{ certificate.server }}"

- name: "Ensure ssl-cert group on target - {{ certificate.domain }}"
  group:
    name: 'ssl-cert'
    state: 'present'
  delegate_to: "{{ certificate.server }}"

- name: "Deploy certificates to target - {{ certificate.domain }}"
  copy:
    src: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ item }}"
    dest: "{{ acme_ssl_destdir }}/{{ certificate.domain }}/{{ item }}"
    mode: 0644
    owner: 'root'
    group: 'ssl-cert'
  delegate_to: "{{ certificate.server }}"
  loop:
    - "{{ certificate.domain }}.key"
    - "{{ certificate.domain }}.csr"
    - "{{ certificate.domain }}.cer"
    - "{{ certificate.domain }}_chain.cer"
    - "{{ certificate.domain }}_fullchain.cer"
    - 'ca.cer'
    - 'ocsp.cer'
  register: 'deployed_cert'

- block:
  - name: 'Determine installed packages'
    package_facts:
      manager: 'auto'
    register: 'acme_ssl_destserver_pkgs'

  - name: 'Reload Apache'
    service:
      name: "{{ apache_service_name }}"
      state: 'reloaded'
    when: >
      (acme_ssl_destserver_pkgs['ansible_facts']['packages']['httpd'] is defined) or
      (acme_ssl_destserver_pkgs['ansible_facts']['packages']['apache2'] is defined)

  - name: 'Reload nginx'
    service:
      name: 'nginx'
      state: 'reloaded'
    when: >
      (acme_ssl_destserver_pkgs['ansible_facts']['packages']['nginx'] is defined) or
      (acme_ssl_destserver_pkgs['ansible_facts']['packages']['nginx-light'] is defined) or
      (acme_ssl_destserver_pkgs['ansible_facts']['packages']['nginx-full'] is defined) or
      (acme_ssl_destserver_pkgs['ansible_facts']['packages']['nginx-extras'] is defined)

  - name: 'Deploy Proxmox certificate and restart pveproxy'
    block:
    - name: 'Copy certificate files'
      copy:
        src: "{{ acme_ssl_basedir }}/{{ certificate.domain }}/{{ item.src }}"
        dest: "/etc/pve/local/{{ item.dest }}"
      delegate_to: "{{ certificate.server }}"
      loop:
        - { src: "{{ certificate.domain }}.key", dest: 'pve-ssl.key' }
        - { src: "{{ certificate.domain }}_fullchain.cer", dest: 'pve-ssl.pem' }
    - name: 'Restart PVEProxy'
      service:
        name: 'pveproxy'
        state: 'restarted'
    when: acme_ssl_destserver_pkgs['ansible_facts']['packages']['pve-manager'] is defined

  - name: 'Deploy Zimbra certificate and restart'
    block:
      - name: 'Deploying Zimbra certificate'
        shell: |
          cd /etc/ssl/acme/{{ certificate.domain }}
          cat {{ certificate.domain }}_chain.cer ca.cer > fullchain_ca.crt
          cd /opt/zimbra/ssl/zimbra/commercial
          cp /etc/ssl/acme/{{ certificate.domain }}/{{ certificate.domain }}.key commercial.key
          sudo -u zimbra /opt/zimbra/bin/zmcertmgr verifycrt comm
          sudo -u zimbra /opt/zimbra/bin/zmcertmgr deploycrt comm /etc/ssl/acme/{{ certificate.domain }}/{{ certificate.domain }}.cer /etc/ssl/acme/{{ certificate.domain }}/fullchain_ca.crt
      - name: 'Restarting Zimbra'
        service:
          name: 'zimbra'
          state: 'restarted'
    when: acme_ssl_destserver_pkgs['ansible_facts']['packages']['zimbra-core'] is defined

  - name: 'Restart slapd'
    service:
      name: 'slapd'
      state: 'restarted'
    when: acme_ssl_destserver_pkgs['ansible_facts']['packages']['slapd'] is defined
  delegate_to: "{{ certificate.server }}"
  when:
    - acme_ssl_reload_services | bool
    - deployed_cert.changed
