---
# Tasks to create a new account on the ACME server
#
- name: 'Create basedir - ACME account'
  file:
    path: "{{ acme_ssl_basedir }}"
    state: 'directory'
    owner: "{{ acme_ssl_owner }}"
    group: "{{ acme_ssl_owner }}"
    mode: 0640

- name: 'Generating new EC SSL key - ACME account'
  community.crypto.openssl_privatekey:
    path: "{{ acme_ssl_account_key }}"
    curve: "{{ acme_ssl_ecparam_curve }}"
    type: 'ECC'
    owner: "{{ acme_ssl_owner }}"
    group: "{{ acme_ssl_owner }}"
    mode: 0640

- name: 'Create ACME account'
  community.crypto.acme_account:
    account_key_src: "{{ acme_ssl_account_key }}"
    state: 'present'
    acme_directory: "{{ acme_ssl_directory }}"
    validate_certs: "{{ acme_ssl_directory_validate }}"
    acme_version: "{{ acme_ssl_directory_version }}"
    terms_agreed: "{{ acme_ssl_terms_agreed }}"
    contact:
      - "mailto:{{ acme_ssl_admin_email }}"
