---
# All tasks required to create the validation for the HTTP-01 challenge
#
- name: Checking token directory on webserver - {{ acme_ssl_domain }}
  file:
    path: "{{ acme_ssl_challenge_location }}/.well-known/acme-challenge"
    state: directory
- name: Place challenge token on webserver - {{ acme_ssl_domain }}
  copy:
    dest: "{{ acme_ssl_challenge_location }}/{{ acme_ssl_challenge['challenge_data'][acme_ssl_domain]['http-01']['resource'] }}"
    content: "{{  acme_ssl_challenge['challenge_data'][acme_ssl_domain]['http-01']['resource_value'] }}"
- name: Remove challenge token from webserver - {{ acme_ssl_domain }}
  file:
    path: "{{ acme_ssl_challenge_location }}/{{ acme_ssl_challenge['challenge_data'][acme_ssl_domain]['http-01']['resource'] }}"
    state: absent
