---
# All tasks required to create the validation for the DNS-01 challenge
#
- name: 'Check required packages'
  package:
    name: [ 'python-dnspython', 'dnsutils' ]
    state: 'present'

- name: "Register challenge DNS records - {{ acme_domain }}"
  nsupdate:
    server: "{{ acme_ssl_nameserver }}"
    ttl: "60"
    type: "TXT"
    zone: "{{ acme_ssl_zone | default(acme_ssl_domain.split('.')[-2:]) }}"
    record:  "{{ acme_ssl_challenge['challenge_data'][acme_ssl_domain]['dns-01']['resource'] }}.{{ acme_ssl_domain }}."
    value: "{{  acme_ssl_challenge['challenge_data'][acme_ssl_domain]['dns-01']['resource_value'] }}"
    state: 'present'
  register: 'dns_registered'
  retries: 5
  delay: 3
  until: not dns_registered.failed
