---
# What: Generate and request certificates via ACME
#
- name: 'Install required packages'
  package:
    name: 'rsync'
    state: 'present'

- name: 'Check ACME account key'
  stat:
    path: "{{ acme_ssl_account_key }}"
  register: 'k'

- name: 'Check ACME account'
  include_tasks:
    file: 'acme_create_account.yml'
  when: not k.stat.exists

- name: 'Process request'
  include_tasks:
    file: 'acme_request.yml'
  loop: "{{ acme_ssl_certificates }}"
  loop_control:
    loop_var: 'certificate'
