---
# What: Generate and request certificates via ACME
#
- name: 'Include distribution specific vars'
  include_vars:
    file: "{{ ansible_facts['os_family'] }}.yml"
- name: 'Install required packages'
  package:
    name: "{{ ssl_packages }}"
    state: 'present'

- name: 'Set certificate owner'
  set_fact:
    acme_ssl_owner: "{{ lookup('env', 'USER') }}"
  when: acme_ssl_owner is not defined

- name: 'Check ACME account key'
  stat:
    path: "{{ acme_ssl_account_key }}"
  register: 'k'

- name: 'Check ACME account'
  include_tasks:
    file: 'acme_create_account.yml'
  when: not k.stat.exists

- name: 'Process request'
  include_tasks:
    file: 'acme_request.yml'
  loop: "{{ acme_ssl_certificates }}"
  loop_control:
    loop_var: 'certificate'
