---
- name: 'Clean up'
  hosts: 'acme-ssl-client'
  gather_facts: false
  ignore_unreachable: true
  tasks:
    - name: 'Remove all ACME files on ACME client'
      file:
        path: '/etc/acme-ssl'
        state: 'absent'
      ignore_errors: true

- name: 'Clean up'
  hosts: 'localhost'
  gather_facts: false
  tasks:
    - name: 'Remove all ACME files on Ansible master'
      file:
        path: '/etc/acme-ssl'
        state: 'absent'
      ignore_errors: true
