---
- name: 'Converge'
  hosts: 'acme-ssl-client'
  become: true
  tasks:
    - name: 'Run Role'
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
    acme_ssl_owner: 'root'
    acme_ssl_certificates:
      - {domain: 'altname.test.lab', altname: ['altname-validated.test.lab'], dns_zone: 'test.lab', server: 'acme-ssl-helper'}
      - {domain: 'dns-validated.test.lab', altname: ['dns.test.lab'], type: 'RSA', challenge: 'dns-01', dns_zone: 'test.lab', server: 'acme-ssl-helper'}
      - {domain: 'dns-splitname.test.lab', altname: ['dns-split.test.lab'], type: 'RSA', challenge: 'dns-01', server: 'acme-ssl-helper'}
      - {domain: 'http-validated.test.lab', challenge: 'http-01', web_dir: '/var/www/html', server: 'acme-ssl-helper'}

    acme_ssl_directory: 'https://pebble:14000/dir'
    acme_ssl_ca_url: 'https://pebble:15000/roots/0'
    acme_ssl_ocsp_url: 'https://pebble:15000/roots/0'
    acme_ssl_directory_validate: false
    acme_ssl_reload_services: true
    acme_ssl_dns_wait: 1
    acme_ssl_basedir: '/tmp/acme-ssl'

    acme_ssl_nameserver: '10.30.50.11'
    acme_ssl_webserver: 'acme-ssl-helper'
    acme_ssl_local_ansible: false
