---
- name: 'Converge'
  hosts: 'acme-ssl-client'
  tasks:
    - include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
    acme_ssl_certificates:
      - { domain: 'altname.test.lab', altname: [ 'altname-validated.test.lab', ], dns_zone: 'test.lab', server: '10.30.50.11' }
      - { domain: 'dns-validated.test.lab', altname: [ 'dns.test.lab' ], type: 'RSA', challenge: 'dns-01',   dns_zone: 'test.lab',     server: '10.30.50.11' }
      - { domain: 'http-validated.test.lab', challenge: 'http-01',  web_dir: '/var/www/html', server: '10.30.50.11' }

    acme_ssl_directory: 'https://pebble:14000/dir'
    acme_ssl_ca_url: 'https://pebble:15000/roots/0'
    acme_ssl_directory_validate: false
    acme_ssl_reload_services: true
    acme_ssl_dns_wait: 1

    acme_ssl_nameserver: '10.30.50.11'
    acme_ssl_webserver: '10.30.50.11'
    acme_ssl_local_ansible: false
