---
- name: 'Setup docker networking'
  hosts: 'localhost'
  gather_facts: true
  tasks:
    - name: 'Create ACMEnet'
      community.general.docker_network:
        name: 'acmenet'
        state: 'present'
        ipam_config:
          - subnet: '10.30.50.0/24'
        labels:
          owner: 'molecule'

    - name: 'Connect Molecule docker to ACMEnet'
      community.general.docker_network:
        name: 'acmenet'
        appends: true
        connected:
          - "{{ ansible_facts['hostname'] }}"
      when: ansible_facts['virtualization_type'] == 'docker'
      ignore_errors: true # it errors out when already connected
  vars:
    ansible_connection: 'local'
