---
dependency:
  name: 'galaxy'
  options:
    requirements-file: 'requirements.yml'
driver:
  name: 'docker'
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "acme-ssl-client"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest"
    command: '/lib/systemd/systemd'
    pre_build_image: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
    docker_networks:
      - name: 'acmenet'
        ipam_config:
          - subnet: "10.30.50.0/24"
    networks:
      - name: "acmenet"
        ipv4_address: '10.30.50.12'
  - name: "acme-ssl-helper"
    image: "geerlingguy/docker-debian10-ansible:latest"
    command: '/lib/systemd/systemd'
    pre_build_image: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
    docker_networks:
      - name: 'acmenet'
        ipam_config:
          - subnet: "10.30.50.0/24"
    networks:
      - name: "acmenet"
        ipv4_address: '10.30.50.11'
  - name: 'pebble'
    image: 'letsencrypt/pebble'
    command: 'pebble --dnsserver 10.30.50.11:53'
    pre_build_image: true
    docker_networks:
      - name: 'acmenet'
        ipam_config:
          - subnet: "10.30.50.0/24"
    networks:
      - name: "acmenet"
        ipv4_address: '10.30.50.10'
provisioner:
  name: 'ansible'
