---
dependency:
  name: 'galaxy'
  options:
    requirements-file: 'requirements.yml'
driver:
  name: ${DRIVER_NAME:-docker}
platforms:
  - name: "acme-ssl-client"
    image: "git.element-networks.nl/containers/${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: '/lib/systemd/systemd'
    pre_build_image: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
    network: 'acmenet'
    ip: '10.30.50.12'
    subnet: '10.30.50.0/24'
    docker_networks:
      - name: 'acmenet'
        ipam_config:
          - subnet: "10.30.50.0/24"
    networks:
      - name: "acmenet"
        ipv4_address: '10.30.50.12'

  - name: "acme-ssl-helper"
    image: "git.element-networks.nl/containers/debian12-ansible:latest"
    command: '/lib/systemd/systemd'
    pre_build_image: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
    network: 'acmenet'
    ip: '10.30.50.11'
    subnet: '10.30.50.0/24'
    docker_networks:
      - name: 'acmenet'
        ipam_config:
          - subnet: "10.30.50.0/24"
    networks:
      - name: "acmenet"
        ipv4_address: '10.30.50.11'
  - name: 'pebble'
    image: 'letsencrypt/pebble'
    command: 'pebble --dnsserver 10.30.50.11:53'
    pre_build_image: true
    privileged: true
    network: 'acmenet'
    ip: '10.30.50.10'
    subnet: '10.30.50.0/24'
    docker_networks:
      - name: 'acmenet'
        ipam_config:
          - subnet: "10.30.50.0/24"
    networks:
      - name: "acmenet"
        ipv4_address: '10.30.50.10'
provisioner:
  name: 'ansible'
