---
- name: 'Converge - DNS01 challenge'
  hosts: 'acme-ssl-client'
  roles:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    acme_ssl_directory: 'https://pebble:14000/dir'
    acme_ssl_directory_validate: false
    acme_ssl_domain: 'dns-validated.test.lab'
    acme_ssl_zone: 'test.lab'
    acme_ssl_nameserver: 'localhost'

- name: 'Converge - HTTP01 challenge'
  hosts: 'acme-ssl-client'
  roles:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    acme_ssl_directory: 'https://pebble:14000/dir'
    acme_ssl_directory_validate: false
    acme_ssl_domain: 'http-validated.test.lab'
    acme_ssl_challenge_type: 'http-01'
    acme_ssl_challenge_location: '/var/www/html'
