---
- name: 'Prepare Molecule and ACME client nodes'
  hosts: 'localhost,acme-ssl-client'
  gather_facts: false
  tasks:
    - name: 'Create SSH directory'
      ansible.builtin.file:
        path: '/root/.ssh'
        state: 'directory'
        mode: 0700
        owner: 'root'
        group: 'root'

    - name: 'Place SSH private key'
      ansible.builtin.copy:
        dest: '/root/.ssh/id_ed25519'
        content: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACDQR3tn7HzM+bpTKgFyWNT1gTcpnHpl4jyOwVt9f+chIQAAAJh1xBcNdcQX
          DQAAAAtzc2gtZWQyNTUxOQAAACDQR3tn7HzM+bpTKgFyWNT1gTcpnHpl4jyOwVt9f+chIQ
          AAAEBRzp1N5iRuu5cf2VOII+BLBMftSn5jesiwKsjW/jTsktBHe2fsfMz5ulMqAXJY1PWB
          NymcemXiPI7BW31/5yEhAAAAFHJvb3RAYWNtZS1zc2wtaGVscGVyAQ==
          -----END OPENSSH PRIVATE KEY-----
        mode: 0600
        owner: 'root'
        group: 'root'
    - name: 'Add Pebble to hosts file'
      ansible.builtin.lineinfile:
        path: '/etc/hosts'
        regexp: '^10\.30\.50\.10'
        line: '10.30.50.10 pebble'
        owner: 'root'
        group: 'root'
        mode: 0644
        unsafe_writes: true

- name: 'Update package cache'
  hosts: 'acme-ssl-client'
  gather_facts: true
  tasks:
    - name: 'Refresh APT'
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'
    - name: 'Refresh YUM'
      ansible.builtin.yum:
        update_cache: true
      when: ansible_facts['os_family'] == 'RedHat'

- name: 'Prepare helper node'
  gather_facts: false
  hosts: 'acme-ssl-helper'
  tasks:
    - name: 'Symlink python'
      ansible.builtin.file:
        path: '/usr/bin/python'
        state: 'link'
        src: '/usr/bin/python3'
    - name: 'Install tools'
      ansible.builtin.apt:
        name:
          - 'pdns-backend-sqlite3'
          - 'sqlite3'
          - 'python3-dnspython'
          - 'dnsutils'
          - 'nginx-light'
          - 'openssh-server'
          - 'ssh'
        state: 'present'
        update_cache: true
    - name: 'Configure nsupdate'
      ansible.builtin.copy:
        dest: '/etc/powerdns/pdns.d/nsupdate.conf'
        content: |
          dnsupdate=yes
          allow-dnsupdate-from=10.30.50.0/24,127.0.0.1/32
        mode: 0644
        owner: 'root'
        group: 'root'
    - name: 'Disable BIND backend'
      ansible.builtin.file:
        path: '/etc/powerdns/pdns.d/bind.conf'
        state: 'absent'
    - name: 'Configure SQLite backend'
      ansible.builtin.copy:
        dest: '/etc/powerdns/pdns.d/sqlite.conf'
        mode: 0644
        content: |
          local-address=0.0.0.0
          launch=gsqlite3
          gsqlite3-database=/var/lib/powerdns/zones.slave.d/powerdns.sqlite3
          master
          daemon
          guardian
    - name: 'Setup PowerDNS DB'
      ansible.builtin.shell: sqlite3 /var/lib/powerdns/zones.slave.d/powerdns.sqlite3 < /usr/share/doc/pdns-backend-sqlite3/schema.sqlite3.sql
      changed_when: true
    - name: 'Correct permissions on DB'
      ansible.builtin.file:
        path: '/var/lib/powerdns/zones.slave.d/powerdns.sqlite3'
        owner: 'pdns'
        group: 'pdns'
    - name: 'Set root authorized_key'
      ansible.posix.authorized_key:
        user: 'root'
        key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINBHe2fsfMz5ulMqAXJY1PWBNymcemXiPI7BW31/5yEh'
        state: 'present'
    - name: 'Allow SSH password logins'
      ansible.builtin.lineinfile:
        path: '/etc/ssh/sshd_config'
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        owner: 'root'
        group: 'root'
        mode: 0644
        unsafe_writes: true
    - name: 'Configure nginx port'
      ansible.builtin.copy:
        dest: '/etc/nginx/sites-enabled/pebble.conf'
        mode: 0644
        content: |
          server {
            listen 5002;
            root /var/www/html;
            location / {
              try_files $uri $uri/ =404;
            }
          }
    - name: 'Restart services'
      ansible.builtin.service:
        name: "{{ service }}"
        state: 'restarted'
      loop:
        - 'pdns'
        - 'nginx'
        - 'ssh'
      loop_control:
        loop_var: 'service'
    - name: 'Create DNS zone'
      ansible.builtin.command: 'pdnsutil create-zone test.lab'
      changed_when: true
      failed_when: false # This only fails when the container isn't freshly created
    - name: 'Fill DNS zone'
      community.general.nsupdate:
        server: 'localhost'
        ttl: 60
        type: 'A'
        zone: 'test.lab.'
        record: "{{ record }}"
        value: '10.30.50.11'
        state: 'present'
      loop:
        - 'dns-validated.test.lab.'
        - 'http-validated.test.lab.'
        - 'altname-validated.test.lab.'
        - 'altname.test.lab.'
      loop_control:
        loop_var: 'record'
