---
- name: 'Prepare Molecule and ACME client nodes'
  hosts: 'localhost,acme-ssl-client'
  gather_facts: false
  tasks:
    - name: 'Create SSH directory'
      file:
        path: '/root/.ssh'
        state: 'directory'
        mode: 0700
        owner: 'root'
        group: 'root'

    - name: 'Place SSH private key'
      copy:
        dest: '/root/.ssh/id_ed25519'
        content: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACDQR3tn7HzM+bpTKgFyWNT1gTcpnHpl4jyOwVt9f+chIQAAAJh1xBcNdcQX
          DQAAAAtzc2gtZWQyNTUxOQAAACDQR3tn7HzM+bpTKgFyWNT1gTcpnHpl4jyOwVt9f+chIQ
          AAAEBRzp1N5iRuu5cf2VOII+BLBMftSn5jesiwKsjW/jTsktBHe2fsfMz5ulMqAXJY1PWB
          NymcemXiPI7BW31/5yEhAAAAFHJvb3RAYWNtZS1zc2wtaGVscGVyAQ==
          -----END OPENSSH PRIVATE KEY-----
        mode: 0600
        owner: 'root'
        group: 'root'
    - name: 'Add Pebble to hosts file'
      lineinfile:
        path: '/etc/hosts'
        regexp: '^10\.30\.50\.2'
        line: '10.30.50.2 pebble'
        owner: 'root'
        group: 'root'
        mode: 0644
        unsafe_writes: true

- name: 'Prepare helper node'
  gather_facts: false
  hosts: 'acme-ssl-helper'
  tasks:
    - name: 'Install tools'
      apt:
        name:
          - 'pdns-backend-sqlite3'
          - 'python-dnspython'
          - 'dnsutils'
          - 'nginx-light'
          - 'openssh-server'
        state: 'present'
        update_cache: true
    - name: 'Configure nsupdate'
      copy:
        dest: '/etc/powerdns/pdns.d/nsupdate.conf'
        content: |
          dnsupdate=yes
          allow-dnsupdate-from=10.30.50.0/24,127.0.0.1/32
        mode: 0644
        owner: 'root'
        group: 'root'
    - name: 'Set root authorized_key'
      authorized_key:
        user: 'root'
        key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINBHe2fsfMz5ulMqAXJY1PWBNymcemXiPI7BW31/5yEh'
        state: 'present'
    - name: 'Allow SSH password logins'
      lineinfile:
        path: '/etc/ssh/sshd_config'
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        owner: 'root'
        group: 'root'
        mode: 0644
        unsafe_writes: true
    - name: 'Configure nginx port'
      copy:
        dest: '/etc/nginx/sites-enabled/pebble.conf'
        content: |
          server {
            listen 5002;
            root /var/www/html;
            location / {
              try_files $uri $uri/ =404;
            }
          }
    - name: 'Restart services'
      service:
        name: "{{ service }}"
        state: 'restarted'
      loop:
        - 'pdns'
        - 'nginx'
        - 'ssh'
      loop_control:
        loop_var: 'service'
    - name: 'Create DNS zone'
      command: 'pdnsutil create-zone test.lab'
      changed_when: true
      ignore_errors: true # This only fails when the container isn't freshly created
    - name: 'Fill DNS zone'
      nsupdate:
        server: 'localhost'
        ttl: 60
        type: 'A'
        zone: 'test.lab.'
        record: "{{ record }}"
        value: '10.30.50.3'
        state: 'present'
      loop:
        - 'dns-validated.test.lab.'
        - 'http-validated.test.lab.'
      loop_control:
        loop_var: 'record'
